apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: ClusterIP
  selector:
    app: web-demo
  ports:
    - port: 2000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-1
  annotations:
    metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/app"

spec:
  ingressClassName: nginx
  rules:
    - host: lb-951022050.eu-south-1.elb.amazonaws.com
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /app(/|$)(.*)
            backend:
              service:
                name: app-svc
                port:
                  number: 2000
